# Generated by Django 6.0.3 on 2026-03-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_case',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
