# Generated by Django 6.0.3 on 2026-03-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_pieces_per_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
