# Generated by Django 6.0.3 on 2026-03-21 07:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='product',
            name='text_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
